name: code-sync

on:
  push:
    branches: [main]

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          echo "Run Clone Step!"
          git config --global init.defaultBranch main
          git init
          git remote add origin https://shenweiyan:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git fetch --all
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
            git branch --track ${branch##*/} $branch
          done
        env:
          GITHUB_REPOSITORY: shenweiyan/WebStackRES
          GITHUB_TOKEN: ${{ secrets.GH_PAT}}
                   
      - name: Push to GitHub 
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/shenweiyan
          dst: github/BioITee
          dst_key: ${{ secrets.ID_RSA }}
          dst_token: ${{ secrets.GH_PAT }}
          src_account_type: user
          dst_account_type: org
          static_list: "WebStackRES"
          force_update: true
          timeout: '0.5h'
